name: Docker Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t raquel460/nodejs-server:v1 .

      - name: Run container from image
        run: |
          docker run -d --name test-container raquel460/nodejs-server:v1

      - name: Check running container
        run: docker ps -a

      - name: Run tests inside container
        run: |
          docker exec test-container npm test

